#! /bin/sh

xrandr --output DVI-I-1 --mode 1920x1080 --rotate normal --rate 144 
#--primary --output VGA-1-1 --mode 1360x760 --rotate normal --rate 60 --right-of DVI-I-1

sxhkd &

#Wallpaper
${HOME}/.fehbg &


#Picom
picom &


#Polybar
~/.config/polybar/launch.sh &

bspc monitor DVI-I-1 -d I II III IV V
#bspc monitor VGA-1-1 -d VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a spotify desktop='IV'
bspc rule -a Steam desktop='V'
bspc rule -a teams desktop='III' 
